spring:
  application:
    name: configuration-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${CONFIGURATION_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    generate-ddl: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/splash/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /car-wash/v3/api-docs
  swagger-ui:
    path: /car-wash/swagger-ui.html

server:
  port: 0
  error:
    include-message: always
